### ISSUE TITLE
Validation markers not handled correctly

### ISSUE THREAD

**Issue by fabien** [hdoro/sanity-plugin-conditional-field#1]
Hi @hdoro thanks for this plugin, it seems to fill in a glaring gap in Sanity Studio right now.

However, it appears that it affects the display of errors within array items (objects). With a field like this:

```
  {
      title: 'Variants',
      name: 'variants',
      type: 'array',
      of: [
        {
          type: 'product.variant',
        },
      ],
      inputComponent: ConditionalField,
      options: {
        condition: (document) => {
          return true; // for testing
        },
      },
    }
```

The validation messages are not shown within the modal `product.variant` form anymore. They only appear top-level (document header).

Perhaps this is related to https://github.com/sanity-io/sanity/issues/2468 as well?

**Comment by opexchanger** [comment]
Loved the plugin, really solved the problem I was having; but I am also not being able to display error messages in the conditional fields, the validation itself works but the message and red background doesnt' show.

**Comment by hdoro** [comment]
V1 hopefully fixes this. Let me know if otherwise, Fabien, and thanks for reporting!

**Comment by fabien** [comment]
@hdoro I will have to check, thanks for working on this!

**Comment by fabien** [comment]
@hdoro I was able to install this new version. However, there seems to be a bug that affects the margins between items:

While the custom price section is hidden, it is fine:

![image](https://user-images.githubusercontent.com/2749/126037709-a00dafdf-d745-42cd-a669-c69c75666612.png)

However, when the section is no longer hidden:

![image](https://user-images.githubusercontent.com/2749/126037749-c0e7832e-3887-438e-abb1-4d8da1e35b38.png)

This is inside of a popover at the moment. If I close it, and reopen the popover, it's fine. The same happens to fields within a fieldset elsewhere in a document (normal layout flow).

It appears to be related to the new HiddenField code and within a fieldset. I'm running Sanity 2.13.0 btw.
